import { Toaster } from '@/components/ui/sonner';
import { cn } from '@/lib/utils';
import { mainFont } from '@/styles/fonts';
import '@/styles/globals.css';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en">
            <body className={cn('antialiased overflow-x-hidden text-foreground bg-muted', mainFont.className)}>
                {/* <TooltipProvider>{children}</TooltipProvider> */}
                {children}
                <Toaster position="top-right" />
            </body>
        </html>
    );
}
